/** @format */

import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import photo from "../public/yichen-image.jpg";

import Navbar from "../component/navbar";
import Work from "../component/work";
import Design from "../component/design";
import Contact from "../component/contact";

export default function Home() {
  return (
    <>
      <div className={styles.container}>
        <Navbar text="#CECCCC" />
        <Head>
          <title>Yichen Zhao</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link
            href="https://fonts.googleapis.com/css2?family=Lora&family=Montserrat&display=swap"
            rel="stylesheet"
          />
        </Head>

        <main className={styles.main}>
          <div className={styles.text}>
            <h3 className={styles.highligh}>Hi, I&prime;m Yichen Zhao,</h3>
            <h1 className={styles.title}>Let&prime;s build something great.</h1>

            <h3 className={styles.description}>
              I&prime;m a &nbsp;
              <span className={styles.highligh}>
                self-taught frontend developer
              </span>
              &nbsp; and &nbsp;
              <span className={styles.highligh}>designer </span>
              based in Seattle.
              <br />I am passionate about building excellent software with
              beautiful UI.
            </h3>
          </div>
          <div className={styles.wrapper}>
            <Image
              src={photo}
              width={300}
              height={300}
              className={styles.img}
              priority={true}
              alt="yichen"
            />
          </div>
        </main>
        <Work />
        <Design />
        <Contact />

        <footer className={styles.footer}>
          <h3>© Yichen Zhao 2022</h3>
        </footer>
      </div>
    </>
  );
}
